---
title: Code of Conduct
---

The International Biometrics Society Australasian Region (IBS-AR) is dedicated to providing a welcoming and harassment-free experience for everyone. We do not tolerate unprofessional or inappropriate conduct, which includes discrimination and harassment, sexual or otherwise. Conference participants should always work towards maintaining an environment free of harassment and discrimination. At the discretion of the IBS-AR conference organisers and/or IBS-AR council, any participants violating these rules may be asked to leave the conference, without any fee refund.

Participants agree to:

- Be considerate in speech and actions, and actively seek to acknowledge and respect the boundaries of fellow attendees at all times.
- Refrain from demeaning, discriminatory, or harassing behaviour and speech. 
- Alert a member of the IBS-AR council or conference organisers if they notice a dangerous situation, someone in distress, or violation of this code of conduct.

Harassment is demeaning or threatening behaviour directed at an individual or a group of people. Harassment includes, but is not limited to,

- Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, person's lifestyle choices and practices, physical appearance, age, race, religion (or lack thereof) or beliefs;
- Unwelcome sexual attention and behaviour including inappropriate sexual propositions; unnecessary touching; verbal or written comments or physical actions of a sexual nature; sexually degrading words used to describe an individual; a display of sexually suggestive objects or pictures; or sexually explicit jokes; and 
- Threatening behaviour including bullying, threat of violence, deliberate intimidation, stalking or incitement of violence.
Reporting


If you are being harassed by a member/guest/participant of/at the IBS-AR Conference, or notice that someone else is being harassed, or have any other concerns, please contact the designated safety officers in the conference team. The current safety officers can be found at TBD. If the person who is harassing you is one of the safety officers, they will recuse themselves from handling your incident and will not be given any information without your explicit consent. We will respond as promptly as we can.
