---
title: Travel
---


<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15876200.543681823!2d134.7546443691398!3d-31.3879577021266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b164ca3b20b34bb%3A0x400ea6ea7695970!2sCanberra%20ACT!5e0!3m2!1sen!2sau!4v1744955267630!5m2!1sen!2sau" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

- By flight, Canberra is:
  - less than an hour from **Sydney**, 
  - about one hour from **Melbourne**,
  - less than two hours from **Adelaide** and **Brisbane**, 
  - about four hours from **Perth**, and 
  - about five hours from **Auckland**.
- **Canberra Airport** is less than 10 minutes from the CBD. 
- Connect to the city via rental car, public bus, taxi or with a rideshare operator (e.g. Uber).
- [**Public transport**](https://www.transport.act.gov.au/tickets-and-myway) accepts Mastercard or Visa (physical card or digital card stored on your smart phone or watch), MyWay+ pass or card, or printed ticket purchased online or machine. 
- If coming from **Sydney**, it is recommended that you catch a bus to Canberra (about 3.5 hours) that departs from Central Station and Sydney airport to Canberra CBD. Bus companies include [Murrays](https://www.murrays.com.au/express-services/canberra-sydney-timetable) and [Greyhound](https://www.greyhound.com.au/buses/sydney-to-canberra).
- The **conference venue**, National Film and Sound Archive of Australia (NFSA), is located close to CBD.
- See **accommodation** options [here](accommodation.html). 

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6513.833971568854!2d149.118880076434!3d-35.283190172718356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b164d413ae340f9%3A0x1c7341ae4d3e2e31!2sNational%20Film%20and%20Sound%20Archive%20of%20Australia%20(NFSA)!5e0!3m2!1sen!2sau!4v1744955618889!5m2!1sen!2sau" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
