---
title: "#BIBC2025 Run Sheet"
format: 
  pdf:
    include-in-header:
      - text: | 
         \usepackage{bera}
         \usepackage{geometry}
         \geometry{
           a4paper,
           total={170mm,257mm},
           left=15mm,
           top=20mm,
           right=15mm,
           bottom=20mm
          }
         \usepackage{fancyhdr}
         \pagestyle{fancy}
         \renewcommand{\arraystretch}{1.3}
execute:
  echo: false
---

```{r}
#| include: false
library(tidyverse)
library(kableExtra)
options(knitr.kable.NA = '')
sessions <- readRDS(here::here("book/data/sessions.rds")) |> 
  filter(type %in% c("Talk", "Keynote", "Invited Session", "Poster")) |> 
  mutate(duration = case_when(type == "Talk" ~ 20,
                              type ==  "Keynote" ~ 50,
                              type ==  "Invited Session" ~ 30,
                               TRUE ~ 0)) |> 
  mutate(order = 1:n(), .by = c(time, location, day)) |> 
  mutate(start = time |> 
             str_extract("^[0-9]+:[0-9]+") |> 
             hm() |> 
             as_datetime(),
           start = start +  dminutes((order - 1) * duration),
           end = start + dminutes(duration),
           time = str_c(format(start, "%H:%M"), "--", format(end, "%H:%M"))) |> 
  select(-location) 
  
room1 <- sessions |> 
  filter(room == "Arc Cinema")
room2 <- sessions |> 
  filter(room == "Theatrette")
poster <- sessions |> 
  filter(type == "Poster")
```


## Arc Cinema

## Tuesday

```{r}
room1 |> 
  kbl(longtable = TRUE)
```

